CREATE TABLE api_users (
    role smallint check (role between 0 and 1),
    id varchar(255) NOT NULL,
    login VARCHAR(255) UNIQUE,
    password VARCHAR(255),
    PRIMARY KEY (id)
);

CREATE TABLE transactions (
    amount NUMERIC(38,2),
    id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    receiver_id BIGINT,
    sender_id BIGINT,
    time_stamps TIMESTAMP(6),
    PRIMARY KEY (ID)
);

CREATE TABLE users (
    balance NUMERIC(38,2),
    id BIGSERIAL NOT NULL,
    document VARCHAR(255) UNIQUE,
    email VARCHAR(255) UNIQUE,
    name VARCHAR(255),
    password VARCHAR(255),
    user_type VARCHAR(255) CHECK (user_type IN ('PF','PJ')),
    PRIMARY KEY (ID)
);

INSERT INTO api_users (login, password, role, id)
VALUES ('pedrobarauna', '$2a$10$NhwMRCyDoHNmzQS1MI4ZSuSbZBXurWxAFACwqFb8139Ru1N.FblJu', 0, 1);